### ISSUE TITLE
Refactor kafka upload tracking

### ISSUE THREAD

**Issue by kumaranvpl** [airtai/airt-service#48]
- [x] Fix db connection saturation issue
- [ ] Pandas df to mysql table as bulk insert
- [ ] Have only one row for each account id in mysql
- [ ] Integrate nbdev-mkdocs
- [ ] Integrate nbqa isort black
- [x] Soonify
- [x] Add and fix mypy.ini
- [x] Group by ApplicationId, ModelId
- [ ] Add HealthCheck for docker
